name: Update China IPs

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: 'Manual trigger'

jobs:
  update-ips:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ipaddress
          pip install requests

      - name: Download IPinfo database and verify size
        run: |
          rm -f country_asn.csv.gz
          wget -q "https://ipinfo.io/data/free/country_asn.csv.gz?token=${{ secrets.IPINFO_TOKEN }}" -O country_asn.csv.gz
          FILE_SIZE=$(stat -c %s country_asn.csv.gz)
          MIN_SIZE=100000  # 假设最小文件大小为 100KB，根据实际情况调整
          if [ "$FILE_SIZE" -lt "$MIN_SIZE" ]; then
            echo "Downloaded file is too small (size: $FILE_SIZE bytes).  It may be incomplete. Aborting."
            exit 1
          fi

      - name: Run script
        run: python main.py

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add china_ips.txt
          git commit -m "Update China IPs" || echo "No changes to commit"
          git push origin main
